//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Conexionpokemon.POKEMONXY {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AutoCompletePokemonNameSoap", Namespace="https://www.pokemonpets.com")]
    public partial class AutoCompletePokemonName : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetRegisteredMembersCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCompletionListPokemonNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCompletionListAttackNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCompletionListUserNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCompletionListItemNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCompletionListRouteNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetUserProfileDisplayOnOffOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetMonsterDetailsSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetMusicOpenOffOperationCompleted;
        
        private System.Threading.SendOrPostCallback returnEnemyPlayerLastMoveTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback returnLatestTurnCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback returnPageRefreshOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetFrameOperationCompleted;
        
        private System.Threading.SendOrPostCallback setNewMoveOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkPvPBattleRedirectOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkChatAlertOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetAutoBattleResultOffOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangeQuickTeamNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetMobileOperationCompleted;
        
        private System.Threading.SendOrPostCallback DisablePvPAlertOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckForcedRefreshOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AutoCompletePokemonName() {
            this.Url = global::Conexionpokemon.Properties.Settings.Default.Conexionpokemon_POKEMONXY_AutoCompletePokemonName;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetRegisteredMembersCountCompletedEventHandler GetRegisteredMembersCountCompleted;
        
        /// <remarks/>
        public event GetCompletionListPokemonNameCompletedEventHandler GetCompletionListPokemonNameCompleted;
        
        /// <remarks/>
        public event GetCompletionListAttackNameCompletedEventHandler GetCompletionListAttackNameCompleted;
        
        /// <remarks/>
        public event GetUserNameCompletedEventHandler GetUserNameCompleted;
        
        /// <remarks/>
        public event GetCompletionListUserNameCompletedEventHandler GetCompletionListUserNameCompleted;
        
        /// <remarks/>
        public event GetCompletionListItemNameCompletedEventHandler GetCompletionListItemNameCompleted;
        
        /// <remarks/>
        public event GetCompletionListRouteNameCompletedEventHandler GetCompletionListRouteNameCompleted;
        
        /// <remarks/>
        public event SetUserProfileDisplayOnOffCompletedEventHandler SetUserProfileDisplayOnOffCompleted;
        
        /// <remarks/>
        public event SetMonsterDetailsSessionCompletedEventHandler SetMonsterDetailsSessionCompleted;
        
        /// <remarks/>
        public event SetMusicOpenOffCompletedEventHandler SetMusicOpenOffCompleted;
        
        /// <remarks/>
        public event returnEnemyPlayerLastMoveTimeCompletedEventHandler returnEnemyPlayerLastMoveTimeCompleted;
        
        /// <remarks/>
        public event returnLatestTurnCountCompletedEventHandler returnLatestTurnCountCompleted;
        
        /// <remarks/>
        public event returnPageRefreshCompletedEventHandler returnPageRefreshCompleted;
        
        /// <remarks/>
        public event SetFrameCompletedEventHandler SetFrameCompleted;
        
        /// <remarks/>
        public event setNewMoveCompletedEventHandler setNewMoveCompleted;
        
        /// <remarks/>
        public event checkPvPBattleRedirectCompletedEventHandler checkPvPBattleRedirectCompleted;
        
        /// <remarks/>
        public event checkChatAlertCompletedEventHandler checkChatAlertCompleted;
        
        /// <remarks/>
        public event SetAutoBattleResultOffCompletedEventHandler SetAutoBattleResultOffCompleted;
        
        /// <remarks/>
        public event ChangeQuickTeamNameCompletedEventHandler ChangeQuickTeamNameCompleted;
        
        /// <remarks/>
        public event SetMobileCompletedEventHandler SetMobileCompleted;
        
        /// <remarks/>
        public event DisablePvPAlertCompletedEventHandler DisablePvPAlertCompleted;
        
        /// <remarks/>
        public event CheckForcedRefreshCompletedEventHandler CheckForcedRefreshCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pokemonpets.com/GetRegisteredMembersCount", RequestNamespace="https://www.pokemonpets.com", ResponseNamespace="https://www.pokemonpets.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRegisteredMembersCount() {
            object[] results = this.Invoke("GetRegisteredMembersCount", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRegisteredMembersCountAsync() {
            this.GetRegisteredMembersCountAsync(null);
        }
        
        /// <remarks/>
        public void GetRegisteredMembersCountAsync(object userState) {
            if ((this.GetRegisteredMembersCountOperationCompleted == null)) {
                this.GetRegisteredMembersCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRegisteredMembersCountOperationCompleted);
            }
            this.InvokeAsync("GetRegisteredMembersCount", new object[0], this.GetRegisteredMembersCountOperationCompleted, userState);
        }
        
        private void OnGetRegisteredMembersCountOperationCompleted(object arg) {
            if ((this.GetRegisteredMembersCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRegisteredMembersCountCompleted(this, new GetRegisteredMembersCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pokemonpets.com/GetCompletionListPokemonName", RequestNamespace="https://www.pokemonpets.com", ResponseNamespace="https://www.pokemonpets.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetCompletionListPokemonName(string prefixText) {
            object[] results = this.Invoke("GetCompletionListPokemonName", new object[] {
                        prefixText});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCompletionListPokemonNameAsync(string prefixText) {
            this.GetCompletionListPokemonNameAsync(prefixText, null);
        }
        
        /// <remarks/>
        public void GetCompletionListPokemonNameAsync(string prefixText, object userState) {
            if ((this.GetCompletionListPokemonNameOperationCompleted == null)) {
                this.GetCompletionListPokemonNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompletionListPokemonNameOperationCompleted);
            }
            this.InvokeAsync("GetCompletionListPokemonName", new object[] {
                        prefixText}, this.GetCompletionListPokemonNameOperationCompleted, userState);
        }
        
        private void OnGetCompletionListPokemonNameOperationCompleted(object arg) {
            if ((this.GetCompletionListPokemonNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompletionListPokemonNameCompleted(this, new GetCompletionListPokemonNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pokemonpets.com/GetCompletionListAttackName", RequestNamespace="https://www.pokemonpets.com", ResponseNamespace="https://www.pokemonpets.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetCompletionListAttackName(string prefixText) {
            object[] results = this.Invoke("GetCompletionListAttackName", new object[] {
                        prefixText});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCompletionListAttackNameAsync(string prefixText) {
            this.GetCompletionListAttackNameAsync(prefixText, null);
        }
        
        /// <remarks/>
        public void GetCompletionListAttackNameAsync(string prefixText, object userState) {
            if ((this.GetCompletionListAttackNameOperationCompleted == null)) {
                this.GetCompletionListAttackNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompletionListAttackNameOperationCompleted);
            }
            this.InvokeAsync("GetCompletionListAttackName", new object[] {
                        prefixText}, this.GetCompletionListAttackNameOperationCompleted, userState);
        }
        
        private void OnGetCompletionListAttackNameOperationCompleted(object arg) {
            if ((this.GetCompletionListAttackNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompletionListAttackNameCompleted(this, new GetCompletionListAttackNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pokemonpets.com/GetUserName", RequestNamespace="https://www.pokemonpets.com", ResponseNamespace="https://www.pokemonpets.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserName(string userId) {
            object[] results = this.Invoke("GetUserName", new object[] {
                        userId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserNameAsync(string userId) {
            this.GetUserNameAsync(userId, null);
        }
        
        /// <remarks/>
        public void GetUserNameAsync(string userId, object userState) {
            if ((this.GetUserNameOperationCompleted == null)) {
                this.GetUserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserNameOperationCompleted);
            }
            this.InvokeAsync("GetUserName", new object[] {
                        userId}, this.GetUserNameOperationCompleted, userState);
        }
        
        private void OnGetUserNameOperationCompleted(object arg) {
            if ((this.GetUserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserNameCompleted(this, new GetUserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pokemonpets.com/GetCompletionListUserName", RequestNamespace="https://www.pokemonpets.com", ResponseNamespace="https://www.pokemonpets.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetCompletionListUserName(string prefixText) {
            object[] results = this.Invoke("GetCompletionListUserName", new object[] {
                        prefixText});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCompletionListUserNameAsync(string prefixText) {
            this.GetCompletionListUserNameAsync(prefixText, null);
        }
        
        /// <remarks/>
        public void GetCompletionListUserNameAsync(string prefixText, object userState) {
            if ((this.GetCompletionListUserNameOperationCompleted == null)) {
                this.GetCompletionListUserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompletionListUserNameOperationCompleted);
            }
            this.InvokeAsync("GetCompletionListUserName", new object[] {
                        prefixText}, this.GetCompletionListUserNameOperationCompleted, userState);
        }
        
        private void OnGetCompletionListUserNameOperationCompleted(object arg) {
            if ((this.GetCompletionListUserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompletionListUserNameCompleted(this, new GetCompletionListUserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pokemonpets.com/GetCompletionListItemName", RequestNamespace="https://www.pokemonpets.com", ResponseNamespace="https://www.pokemonpets.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetCompletionListItemName(string prefixText) {
            object[] results = this.Invoke("GetCompletionListItemName", new object[] {
                        prefixText});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCompletionListItemNameAsync(string prefixText) {
            this.GetCompletionListItemNameAsync(prefixText, null);
        }
        
        /// <remarks/>
        public void GetCompletionListItemNameAsync(string prefixText, object userState) {
            if ((this.GetCompletionListItemNameOperationCompleted == null)) {
                this.GetCompletionListItemNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompletionListItemNameOperationCompleted);
            }
            this.InvokeAsync("GetCompletionListItemName", new object[] {
                        prefixText}, this.GetCompletionListItemNameOperationCompleted, userState);
        }
        
        private void OnGetCompletionListItemNameOperationCompleted(object arg) {
            if ((this.GetCompletionListItemNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompletionListItemNameCompleted(this, new GetCompletionListItemNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pokemonpets.com/GetCompletionListRouteName", RequestNamespace="https://www.pokemonpets.com", ResponseNamespace="https://www.pokemonpets.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetCompletionListRouteName(string prefixText) {
            object[] results = this.Invoke("GetCompletionListRouteName", new object[] {
                        prefixText});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCompletionListRouteNameAsync(string prefixText) {
            this.GetCompletionListRouteNameAsync(prefixText, null);
        }
        
        /// <remarks/>
        public void GetCompletionListRouteNameAsync(string prefixText, object userState) {
            if ((this.GetCompletionListRouteNameOperationCompleted == null)) {
                this.GetCompletionListRouteNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompletionListRouteNameOperationCompleted);
            }
            this.InvokeAsync("GetCompletionListRouteName", new object[] {
                        prefixText}, this.GetCompletionListRouteNameOperationCompleted, userState);
        }
        
        private void OnGetCompletionListRouteNameOperationCompleted(object arg) {
            if ((this.GetCompletionListRouteNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompletionListRouteNameCompleted(this, new GetCompletionListRouteNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pokemonpets.com/SetUserProfileDisplayOnOff", RequestNamespace="https://www.pokemonpets.com", ResponseNamespace="https://www.pokemonpets.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetUserProfileDisplayOnOff(string srParam) {
            this.Invoke("SetUserProfileDisplayOnOff", new object[] {
                        srParam});
        }
        
        /// <remarks/>
        public void SetUserProfileDisplayOnOffAsync(string srParam) {
            this.SetUserProfileDisplayOnOffAsync(srParam, null);
        }
        
        /// <remarks/>
        public void SetUserProfileDisplayOnOffAsync(string srParam, object userState) {
            if ((this.SetUserProfileDisplayOnOffOperationCompleted == null)) {
                this.SetUserProfileDisplayOnOffOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetUserProfileDisplayOnOffOperationCompleted);
            }
            this.InvokeAsync("SetUserProfileDisplayOnOff", new object[] {
                        srParam}, this.SetUserProfileDisplayOnOffOperationCompleted, userState);
        }
        
        private void OnSetUserProfileDisplayOnOffOperationCompleted(object arg) {
            if ((this.SetUserProfileDisplayOnOffCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetUserProfileDisplayOnOffCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pokemonpets.com/SetMonsterDetailsSession", RequestNamespace="https://www.pokemonpets.com", ResponseNamespace="https://www.pokemonpets.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetMonsterDetailsSession(string srSessionName, string srValue) {
            this.Invoke("SetMonsterDetailsSession", new object[] {
                        srSessionName,
                        srValue});
        }
        
        /// <remarks/>
        public void SetMonsterDetailsSessionAsync(string srSessionName, string srValue) {
            this.SetMonsterDetailsSessionAsync(srSessionName, srValue, null);
        }
        
        /// <remarks/>
        public void SetMonsterDetailsSessionAsync(string srSessionName, string srValue, object userState) {
            if ((this.SetMonsterDetailsSessionOperationCompleted == null)) {
                this.SetMonsterDetailsSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetMonsterDetailsSessionOperationCompleted);
            }
            this.InvokeAsync("SetMonsterDetailsSession", new object[] {
                        srSessionName,
                        srValue}, this.SetMonsterDetailsSessionOperationCompleted, userState);
        }
        
        private void OnSetMonsterDetailsSessionOperationCompleted(object arg) {
            if ((this.SetMonsterDetailsSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetMonsterDetailsSessionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pokemonpets.com/SetMusicOpenOff", RequestNamespace="https://www.pokemonpets.com", ResponseNamespace="https://www.pokemonpets.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetMusicOpenOff(string srValue) {
            this.Invoke("SetMusicOpenOff", new object[] {
                        srValue});
        }
        
        /// <remarks/>
        public void SetMusicOpenOffAsync(string srValue) {
            this.SetMusicOpenOffAsync(srValue, null);
        }
        
        /// <remarks/>
        public void SetMusicOpenOffAsync(string srValue, object userState) {
            if ((this.SetMusicOpenOffOperationCompleted == null)) {
                this.SetMusicOpenOffOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetMusicOpenOffOperationCompleted);
            }
            this.InvokeAsync("SetMusicOpenOff", new object[] {
                        srValue}, this.SetMusicOpenOffOperationCompleted, userState);
        }
        
        private void OnSetMusicOpenOffOperationCompleted(object arg) {
            if ((this.SetMusicOpenOffCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetMusicOpenOffCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pokemonpets.com/returnEnemyPlayerLastMoveTime", RequestNamespace="https://www.pokemonpets.com", ResponseNamespace="https://www.pokemonpets.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] returnEnemyPlayerLastMoveTime() {
            object[] results = this.Invoke("returnEnemyPlayerLastMoveTime", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void returnEnemyPlayerLastMoveTimeAsync() {
            this.returnEnemyPlayerLastMoveTimeAsync(null);
        }
        
        /// <remarks/>
        public void returnEnemyPlayerLastMoveTimeAsync(object userState) {
            if ((this.returnEnemyPlayerLastMoveTimeOperationCompleted == null)) {
                this.returnEnemyPlayerLastMoveTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreturnEnemyPlayerLastMoveTimeOperationCompleted);
            }
            this.InvokeAsync("returnEnemyPlayerLastMoveTime", new object[0], this.returnEnemyPlayerLastMoveTimeOperationCompleted, userState);
        }
        
        private void OnreturnEnemyPlayerLastMoveTimeOperationCompleted(object arg) {
            if ((this.returnEnemyPlayerLastMoveTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.returnEnemyPlayerLastMoveTimeCompleted(this, new returnEnemyPlayerLastMoveTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pokemonpets.com/returnLatestTurnCount", RequestNamespace="https://www.pokemonpets.com", ResponseNamespace="https://www.pokemonpets.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string returnLatestTurnCount() {
            object[] results = this.Invoke("returnLatestTurnCount", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void returnLatestTurnCountAsync() {
            this.returnLatestTurnCountAsync(null);
        }
        
        /// <remarks/>
        public void returnLatestTurnCountAsync(object userState) {
            if ((this.returnLatestTurnCountOperationCompleted == null)) {
                this.returnLatestTurnCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreturnLatestTurnCountOperationCompleted);
            }
            this.InvokeAsync("returnLatestTurnCount", new object[0], this.returnLatestTurnCountOperationCompleted, userState);
        }
        
        private void OnreturnLatestTurnCountOperationCompleted(object arg) {
            if ((this.returnLatestTurnCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.returnLatestTurnCountCompleted(this, new returnLatestTurnCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pokemonpets.com/returnPageRefresh", RequestNamespace="https://www.pokemonpets.com", ResponseNamespace="https://www.pokemonpets.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string returnPageRefresh() {
            object[] results = this.Invoke("returnPageRefresh", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void returnPageRefreshAsync() {
            this.returnPageRefreshAsync(null);
        }
        
        /// <remarks/>
        public void returnPageRefreshAsync(object userState) {
            if ((this.returnPageRefreshOperationCompleted == null)) {
                this.returnPageRefreshOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreturnPageRefreshOperationCompleted);
            }
            this.InvokeAsync("returnPageRefresh", new object[0], this.returnPageRefreshOperationCompleted, userState);
        }
        
        private void OnreturnPageRefreshOperationCompleted(object arg) {
            if ((this.returnPageRefreshCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.returnPageRefreshCompleted(this, new returnPageRefreshCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pokemonpets.com/SetFrame", RequestNamespace="https://www.pokemonpets.com", ResponseNamespace="https://www.pokemonpets.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetFrame(string srValue) {
            this.Invoke("SetFrame", new object[] {
                        srValue});
        }
        
        /// <remarks/>
        public void SetFrameAsync(string srValue) {
            this.SetFrameAsync(srValue, null);
        }
        
        /// <remarks/>
        public void SetFrameAsync(string srValue, object userState) {
            if ((this.SetFrameOperationCompleted == null)) {
                this.SetFrameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetFrameOperationCompleted);
            }
            this.InvokeAsync("SetFrame", new object[] {
                        srValue}, this.SetFrameOperationCompleted, userState);
        }
        
        private void OnSetFrameOperationCompleted(object arg) {
            if ((this.SetFrameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetFrameCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pokemonpets.com/setNewMove", RequestNamespace="https://www.pokemonpets.com", ResponseNamespace="https://www.pokemonpets.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string setNewMove(string panelId, string uniquePokemonId, string replaceMove, string newMove, string srLanguage) {
            object[] results = this.Invoke("setNewMove", new object[] {
                        panelId,
                        uniquePokemonId,
                        replaceMove,
                        newMove,
                        srLanguage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void setNewMoveAsync(string panelId, string uniquePokemonId, string replaceMove, string newMove, string srLanguage) {
            this.setNewMoveAsync(panelId, uniquePokemonId, replaceMove, newMove, srLanguage, null);
        }
        
        /// <remarks/>
        public void setNewMoveAsync(string panelId, string uniquePokemonId, string replaceMove, string newMove, string srLanguage, object userState) {
            if ((this.setNewMoveOperationCompleted == null)) {
                this.setNewMoveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetNewMoveOperationCompleted);
            }
            this.InvokeAsync("setNewMove", new object[] {
                        panelId,
                        uniquePokemonId,
                        replaceMove,
                        newMove,
                        srLanguage}, this.setNewMoveOperationCompleted, userState);
        }
        
        private void OnsetNewMoveOperationCompleted(object arg) {
            if ((this.setNewMoveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setNewMoveCompleted(this, new setNewMoveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pokemonpets.com/checkPvPBattleRedirect", RequestNamespace="https://www.pokemonpets.com", ResponseNamespace="https://www.pokemonpets.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string checkPvPBattleRedirect() {
            object[] results = this.Invoke("checkPvPBattleRedirect", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void checkPvPBattleRedirectAsync() {
            this.checkPvPBattleRedirectAsync(null);
        }
        
        /// <remarks/>
        public void checkPvPBattleRedirectAsync(object userState) {
            if ((this.checkPvPBattleRedirectOperationCompleted == null)) {
                this.checkPvPBattleRedirectOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckPvPBattleRedirectOperationCompleted);
            }
            this.InvokeAsync("checkPvPBattleRedirect", new object[0], this.checkPvPBattleRedirectOperationCompleted, userState);
        }
        
        private void OncheckPvPBattleRedirectOperationCompleted(object arg) {
            if ((this.checkPvPBattleRedirectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkPvPBattleRedirectCompleted(this, new checkPvPBattleRedirectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pokemonpets.com/checkChatAlert", RequestNamespace="https://www.pokemonpets.com", ResponseNamespace="https://www.pokemonpets.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string checkChatAlert() {
            object[] results = this.Invoke("checkChatAlert", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void checkChatAlertAsync() {
            this.checkChatAlertAsync(null);
        }
        
        /// <remarks/>
        public void checkChatAlertAsync(object userState) {
            if ((this.checkChatAlertOperationCompleted == null)) {
                this.checkChatAlertOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckChatAlertOperationCompleted);
            }
            this.InvokeAsync("checkChatAlert", new object[0], this.checkChatAlertOperationCompleted, userState);
        }
        
        private void OncheckChatAlertOperationCompleted(object arg) {
            if ((this.checkChatAlertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkChatAlertCompleted(this, new checkChatAlertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pokemonpets.com/SetAutoBattleResultOff", RequestNamespace="https://www.pokemonpets.com", ResponseNamespace="https://www.pokemonpets.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetAutoBattleResultOff(string srValue, string srLang) {
            object[] results = this.Invoke("SetAutoBattleResultOff", new object[] {
                        srValue,
                        srLang});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetAutoBattleResultOffAsync(string srValue, string srLang) {
            this.SetAutoBattleResultOffAsync(srValue, srLang, null);
        }
        
        /// <remarks/>
        public void SetAutoBattleResultOffAsync(string srValue, string srLang, object userState) {
            if ((this.SetAutoBattleResultOffOperationCompleted == null)) {
                this.SetAutoBattleResultOffOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetAutoBattleResultOffOperationCompleted);
            }
            this.InvokeAsync("SetAutoBattleResultOff", new object[] {
                        srValue,
                        srLang}, this.SetAutoBattleResultOffOperationCompleted, userState);
        }
        
        private void OnSetAutoBattleResultOffOperationCompleted(object arg) {
            if ((this.SetAutoBattleResultOffCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetAutoBattleResultOffCompleted(this, new SetAutoBattleResultOffCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pokemonpets.com/ChangeQuickTeamName", RequestNamespace="https://www.pokemonpets.com", ResponseNamespace="https://www.pokemonpets.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChangeQuickTeamName(string srOrgTeamName, string srNewTeamName, string srLang) {
            object[] results = this.Invoke("ChangeQuickTeamName", new object[] {
                        srOrgTeamName,
                        srNewTeamName,
                        srLang});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ChangeQuickTeamNameAsync(string srOrgTeamName, string srNewTeamName, string srLang) {
            this.ChangeQuickTeamNameAsync(srOrgTeamName, srNewTeamName, srLang, null);
        }
        
        /// <remarks/>
        public void ChangeQuickTeamNameAsync(string srOrgTeamName, string srNewTeamName, string srLang, object userState) {
            if ((this.ChangeQuickTeamNameOperationCompleted == null)) {
                this.ChangeQuickTeamNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeQuickTeamNameOperationCompleted);
            }
            this.InvokeAsync("ChangeQuickTeamName", new object[] {
                        srOrgTeamName,
                        srNewTeamName,
                        srLang}, this.ChangeQuickTeamNameOperationCompleted, userState);
        }
        
        private void OnChangeQuickTeamNameOperationCompleted(object arg) {
            if ((this.ChangeQuickTeamNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeQuickTeamNameCompleted(this, new ChangeQuickTeamNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pokemonpets.com/SetMobile", RequestNamespace="https://www.pokemonpets.com", ResponseNamespace="https://www.pokemonpets.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetMobile(string srValue) {
            this.Invoke("SetMobile", new object[] {
                        srValue});
        }
        
        /// <remarks/>
        public void SetMobileAsync(string srValue) {
            this.SetMobileAsync(srValue, null);
        }
        
        /// <remarks/>
        public void SetMobileAsync(string srValue, object userState) {
            if ((this.SetMobileOperationCompleted == null)) {
                this.SetMobileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetMobileOperationCompleted);
            }
            this.InvokeAsync("SetMobile", new object[] {
                        srValue}, this.SetMobileOperationCompleted, userState);
        }
        
        private void OnSetMobileOperationCompleted(object arg) {
            if ((this.SetMobileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetMobileCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pokemonpets.com/DisablePvPAlert", RequestNamespace="https://www.pokemonpets.com", ResponseNamespace="https://www.pokemonpets.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DisablePvPAlert(string srBattleId) {
            this.Invoke("DisablePvPAlert", new object[] {
                        srBattleId});
        }
        
        /// <remarks/>
        public void DisablePvPAlertAsync(string srBattleId) {
            this.DisablePvPAlertAsync(srBattleId, null);
        }
        
        /// <remarks/>
        public void DisablePvPAlertAsync(string srBattleId, object userState) {
            if ((this.DisablePvPAlertOperationCompleted == null)) {
                this.DisablePvPAlertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDisablePvPAlertOperationCompleted);
            }
            this.InvokeAsync("DisablePvPAlert", new object[] {
                        srBattleId}, this.DisablePvPAlertOperationCompleted, userState);
        }
        
        private void OnDisablePvPAlertOperationCompleted(object arg) {
            if ((this.DisablePvPAlertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DisablePvPAlertCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.pokemonpets.com/CheckForcedRefresh", RequestNamespace="https://www.pokemonpets.com", ResponseNamespace="https://www.pokemonpets.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckForcedRefresh() {
            object[] results = this.Invoke("CheckForcedRefresh", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckForcedRefreshAsync() {
            this.CheckForcedRefreshAsync(null);
        }
        
        /// <remarks/>
        public void CheckForcedRefreshAsync(object userState) {
            if ((this.CheckForcedRefreshOperationCompleted == null)) {
                this.CheckForcedRefreshOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckForcedRefreshOperationCompleted);
            }
            this.InvokeAsync("CheckForcedRefresh", new object[0], this.CheckForcedRefreshOperationCompleted, userState);
        }
        
        private void OnCheckForcedRefreshOperationCompleted(object arg) {
            if ((this.CheckForcedRefreshCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckForcedRefreshCompleted(this, new CheckForcedRefreshCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetRegisteredMembersCountCompletedEventHandler(object sender, GetRegisteredMembersCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRegisteredMembersCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRegisteredMembersCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetCompletionListPokemonNameCompletedEventHandler(object sender, GetCompletionListPokemonNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompletionListPokemonNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompletionListPokemonNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetCompletionListAttackNameCompletedEventHandler(object sender, GetCompletionListAttackNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompletionListAttackNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompletionListAttackNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetUserNameCompletedEventHandler(object sender, GetUserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetCompletionListUserNameCompletedEventHandler(object sender, GetCompletionListUserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompletionListUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompletionListUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetCompletionListItemNameCompletedEventHandler(object sender, GetCompletionListItemNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompletionListItemNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompletionListItemNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetCompletionListRouteNameCompletedEventHandler(object sender, GetCompletionListRouteNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompletionListRouteNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompletionListRouteNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void SetUserProfileDisplayOnOffCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void SetMonsterDetailsSessionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void SetMusicOpenOffCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void returnEnemyPlayerLastMoveTimeCompletedEventHandler(object sender, returnEnemyPlayerLastMoveTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class returnEnemyPlayerLastMoveTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal returnEnemyPlayerLastMoveTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void returnLatestTurnCountCompletedEventHandler(object sender, returnLatestTurnCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class returnLatestTurnCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal returnLatestTurnCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void returnPageRefreshCompletedEventHandler(object sender, returnPageRefreshCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class returnPageRefreshCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal returnPageRefreshCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void SetFrameCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void setNewMoveCompletedEventHandler(object sender, setNewMoveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setNewMoveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setNewMoveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void checkPvPBattleRedirectCompletedEventHandler(object sender, checkPvPBattleRedirectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkPvPBattleRedirectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkPvPBattleRedirectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void checkChatAlertCompletedEventHandler(object sender, checkChatAlertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkChatAlertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkChatAlertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void SetAutoBattleResultOffCompletedEventHandler(object sender, SetAutoBattleResultOffCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetAutoBattleResultOffCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetAutoBattleResultOffCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ChangeQuickTeamNameCompletedEventHandler(object sender, ChangeQuickTeamNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeQuickTeamNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangeQuickTeamNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void SetMobileCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void DisablePvPAlertCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void CheckForcedRefreshCompletedEventHandler(object sender, CheckForcedRefreshCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckForcedRefreshCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckForcedRefreshCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591